#
# Makefile for optimizer
#
# src/backend/gporca/libgpdbcost/src/Makefile
#

subdir = gpcontrib/gp_orca/gporca/libgpdbcost/src
top_builddir = ../../../../..
include $(top_builddir)/src/Makefile.global

include $(top_srcdir)/gpcontrib/gp_orca/gporca/gporca.mk

OBJS        = CCostModelGPDB.o \
              CCostModelParamsGPDB.o \
              ICostModel.o

include $(top_srcdir)/src/backend/common.mk

