# Makefile for optimizer
#
# src/backend/gporca/Makefile
#

subdir = gpcontrib/gp_orca/gporca
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS     = libgpos libgpdbcost libnaucrates libgpopt

include $(top_srcdir)/src/backend/common.mk
