#
# Makefile for optimizer
#
# src/backend/gporca/libgpopt/src/optimizer/Makefile
#

subdir = gpcontrib/gp_orca/gporca/libgpopt/src/optimizer
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global

include $(top_srcdir)/gpcontrib/gp_orca/gporca/gporca.mk

OBJS        = COptimizer.o COptimizerConfig.o

include $(top_srcdir)/src/backend/common.mk

