#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for gpopt
#
#-------------------------------------------------------------------------

subdir = gpcontrib/gp_orca/gpopt/config
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

include $(top_srcdir)/gpcontrib/gp_orca/gpopt/gpopt.mk

OBJS = CConfigParamMapping.o

include $(top_srcdir)/src/backend/common.mk
