#
# Makefile for optimizer
#
# src/backend/gporca/Makefile
#

subdir = gpcontrib/gp_orca/gporca
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS     = src

include $(top_srcdir)/src/backend/common.mk
