---

version: "3"
services:
  mdw:
    image: "hub.adsw.io/library/gpdb6_regress:${BRANCH_NAME}"
    working_dir: /home/gpadmin
    hostname: mdw
    volumes:
      - "$PWD/ssh_keys/id_rsa:/home/gpadmin/.ssh/id_rsa"
      - "$PWD/ssh_keys/id_rsa.pub:/home/gpadmin/.ssh/id_rsa.pub"
      - "$PWD/allure-results:/tmp/allure-results"
    privileged: true
    sysctls:
      kernel.sem: 500 1024000 200 4096
    entrypoint: >
      bash -c "mkdir -p /data/gpdata && chmod -R 777 /data &&
      echo 'gpadmin ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers &&
      tail -f /home/gpadmin/gpdb_src/README.md"
  sdw1:
    image: "hub.adsw.io/library/gpdb6_regress:${BRANCH_NAME}"
    privileged: true
    hostname: sdw1
    volumes:
      - "$PWD/ssh_keys/id_rsa:/home/gpadmin/.ssh/id_rsa"
      - "$PWD/ssh_keys/id_rsa.pub:/home/gpadmin/.ssh/id_rsa.pub"
    sysctls:
      kernel.sem: 500 1024000 200 4096
    entrypoint: >
      bash -c "mkdir -p /data/gpdata && chmod -R 777 /data &&
      source gpdb_src/concourse/scripts/common.bash && install_gpdb &&
      ./gpdb_src/concourse/scripts/setup_gpadmin_user.bash &&
      echo 'gpadmin ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers &&
      tail -f /home/gpadmin/gpdb_src/README.md"
  sdw2:
    image: "hub.adsw.io/library/gpdb6_regress:${BRANCH_NAME}"
    privileged: true
    hostname: sdw2
    volumes:
      - "$PWD/ssh_keys/id_rsa:/home/gpadmin/.ssh/id_rsa"
      - "$PWD/ssh_keys/id_rsa.pub:/home/gpadmin/.ssh/id_rsa.pub"
    sysctls:
      kernel.sem: 500 1024000 200 4096
    entrypoint: >
      bash -c "mkdir -p /data/gpdata && chmod -R 777 /data &&
      source gpdb_src/concourse/scripts/common.bash && install_gpdb &&
      ./gpdb_src/concourse/scripts/setup_gpadmin_user.bash &&
      echo 'gpadmin ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers &&
      tail -f /home/gpadmin/gpdb_src/README.md"
  sdw3:
    image: "hub.adsw.io/library/gpdb6_regress:${BRANCH_NAME}"
    privileged: true
    hostname: sdw3
    volumes:
      - "$PWD/ssh_keys/id_rsa:/home/gpadmin/.ssh/id_rsa"
      - "$PWD/ssh_keys/id_rsa.pub:/home/gpadmin/.ssh/id_rsa.pub"
    sysctls:
      kernel.sem: 500 1024000 200 4096
    entrypoint: >
      bash -c "mkdir -p /data/gpdata && chmod -R 777 /data &&
      source gpdb_src/concourse/scripts/common.bash && install_gpdb &&
      ./gpdb_src/concourse/scripts/setup_gpadmin_user.bash &&
      echo 'gpadmin ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers &&
      tail -f /home/gpadmin/gpdb_src/README.md"
