---

version: "3"
services:
  mdw:
    image: "hub.adsw.io/library/gpdb_regress:${BRANCH_NAME}"
    working_dir: /home/gpadmin
    hostname: mdw
    volumes:
      - "$PWD/ssh_keys/id_rsa:/home/gpadmin/.ssh/id_rsa"
      - "$PWD/ssh_keys/id_rsa.pub:/home/gpadmin/.ssh/id_rsa.pub"
      - "$PWD/arenadata:/home/gpadmin/gpdb_src/arenadata"
      - "$PWD/gpMgmt:/home/gpadmin/gpdb_src/gpMgmt"
      - "$PWD/allure-results:/tmp/allure-results"
    privileged: true
    entrypoint: >
      bash -c "mkdir -p /data/gpdata && chmod -R 777 /data &&
      sysctl 'kernel.sem=500 1024000 200 4096' &&
      pip --retries 10 install --ignore-installed pip allure-behave==2.4.0 &&
      getent hosts sdw1 sdw2 sdw3 >> /etc/hosts &&
      tail -f /home/gpadmin/gpdb_src/README.md"
  sdw1:
    image: "hub.adsw.io/library/gpdb_regress:${BRANCH_NAME}"
    privileged: true
    hostname: sdw1
    volumes:
      - "$PWD/ssh_keys/id_rsa:/home/gpadmin/.ssh/id_rsa"
      - "$PWD/ssh_keys/id_rsa.pub:/home/gpadmin/.ssh/id_rsa.pub"
    entrypoint: >
      bash -c "mkdir -p /data/gpdata && chmod -R 777 /data &&
      source gpdb_src/concourse/scripts/common.bash && install_gpdb &&
      ./gpdb_src/concourse/scripts/setup_gpadmin_user.bash &&
      sysctl 'kernel.sem=500 1024000 200 4096' &&
      getent hosts mdw sdw2 sdw3 >> /etc/hosts &&
      tail -f /home/gpadmin/gpdb_src/README.md"
  sdw2:
    image: "hub.adsw.io/library/gpdb_regress:${BRANCH_NAME}"
    privileged: true
    hostname: sdw2
    volumes:
      - "$PWD/ssh_keys/id_rsa:/home/gpadmin/.ssh/id_rsa"
      - "$PWD/ssh_keys/id_rsa.pub:/home/gpadmin/.ssh/id_rsa.pub"
    entrypoint: >
      bash -c "mkdir -p /data/gpdata && chmod -R 777 /data &&
      source gpdb_src/concourse/scripts/common.bash && install_gpdb &&
      ./gpdb_src/concourse/scripts/setup_gpadmin_user.bash &&
      sysctl 'kernel.sem=500 1024000 200 4096' &&
      getent hosts sdw1 mdw sdw3 >> /etc/hosts &&
      tail -f /home/gpadmin/gpdb_src/README.md"
  sdw3:
    image: "hub.adsw.io/library/gpdb_regress:${BRANCH_NAME}"
    privileged: true
    hostname: sdw3
    volumes:
      - "$PWD/ssh_keys/id_rsa:/home/gpadmin/.ssh/id_rsa"
      - "$PWD/ssh_keys/id_rsa.pub:/home/gpadmin/.ssh/id_rsa.pub"
    entrypoint: >
      bash -c "mkdir -p /data/gpdata && chmod -R 777 /data &&
      source gpdb_src/concourse/scripts/common.bash && install_gpdb &&
      ./gpdb_src/concourse/scripts/setup_gpadmin_user.bash &&
      sysctl 'kernel.sem=500 1024000 200 4096' &&
      getent hosts sdw1 sdw2 mdw >> /etc/hosts &&
      tail -f /home/gpadmin/gpdb_src/README.md"
