---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: gcr.io/data-gpdb-public-images/gpdb6-rocky8-build
    tag: latest

inputs:
  - name: gpdb_src
  - name: bin_gpdb

run:
  path: gpdb_src/concourse/scripts/verify_gpdb_versions.bash
