#
# Makefile for optimizer
#
# src/backend/gporca/libgpos/src/string/Makefile
#

subdir = gpcontrib/gp_orca/gporca/libgpos/src/string
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global

include $(top_srcdir)/gpcontrib/gp_orca/gporca/gporca.mk

OBJS        = CStringStatic.o \
              CWString.o \
              CWStringBase.o \
              CWStringConst.o \
              CWStringDynamic.o \
              CWStringStatic.o

include $(top_srcdir)/src/backend/common.mk

